// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ApiMap struct {
	ID        int64
	UserID    int64
	Key       string
	TargetUrl string
	Policies  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
