// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ApiMap struct {
	ID        int64
	Key       string
	TargetUrl sql.NullString
}

type User struct {
	ID       int64
	Username string
	Email    string
	Password string
}
