// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createApiMap = `-- name: CreateApiMap :exec
INSERT INTO api_maps (key, target_url) VALUES (?, ?)
`

type CreateApiMapParams struct {
	Key       string
	TargetUrl sql.NullString
}

func (q *Queries) CreateApiMap(ctx context.Context, arg CreateApiMapParams) error {
	_, err := q.db.ExecContext(ctx, createApiMap, arg.Key, arg.TargetUrl)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (username, email, password) VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Username string
	Email    string
	Password string
}

// ----------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Email, arg.Password)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTargetUrlByApiKey = `-- name: GetTargetUrlByApiKey :one
SELECT id, "key", target_url FROM api_maps WHERE key = ?
`

func (q *Queries) GetTargetUrlByApiKey(ctx context.Context, key string) (ApiMap, error) {
	row := q.db.QueryRowContext(ctx, getTargetUrlByApiKey, key)
	var i ApiMap
	err := row.Scan(&i.ID, &i.Key, &i.TargetUrl)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password FROM users WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const updateApiMapByKey = `-- name: UpdateApiMapByKey :exec
UPDATE api_maps SET target_url = ? WHERE key = ?
`

type UpdateApiMapByKeyParams struct {
	TargetUrl sql.NullString
	Key       string
}

func (q *Queries) UpdateApiMapByKey(ctx context.Context, arg UpdateApiMapByKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateApiMapByKey, arg.TargetUrl, arg.Key)
	return err
}
